### ISSUE TITLE
building javascript files not working

### ISSUE THREAD

**Issue by waozixyz** [render-examples/sveltekit-static#6]
When using a javascript file for an rss feed, the build folder does not contain the file.

I do not encounter any issue when using the svllte-kit dev server, however when i bulid it using the sveltekit-static adapter the file does not appear in the 'build' folder

im using a similar setup as in this example:
https://www.davidwparker.com/posts/how-to-make-an-rss-feed-in-sveltekit

**Comment by metonym** [comment]
Could you try using the Node adapter? I'm not sure if that RSS feed can be achieved using the static adapter.

SvelteKit has a [HackerNews example](https://github.com/sveltejs/kit/tree/master/examples/hn.svelte.dev) that uses the Netlify adapter. The only page that is prerendered is `about/index.html`. Everything else has a server component.

**Comment by waotzi** [comment]
well i could use the node adapter, but i want to host it as a static site for now, to reduce server costs :/
